apiVersion: v1
kind: ConfigMap
metadata:
  name: sentinel-agent-config
  namespace: default
data:
  KAFKA_BROKER: "hermes-kafka-kafka-bootstrap.kafka.svc.cluster.local:9092"
  KAFKA_PURGE_TOPIC: "cache-purge-events"
  AUTO_REMEDIATE_ENABLED: "true"