apiVersion: apps/v1
kind: Deployment
metadata:
  name: eu-edge-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eu-edge
  template:
    metadata:
      labels:
        app: eu-edge
    spec:
      # Lock this proxy to the EU West region
      nodeSelector:
        topology.kubernetes.io/region: "eu-west"
      containers:
        # Container 1: The NGINX Reverse Proxy
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config-volume
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: shared-cache-volume
              mountPath: /var/cache/nginx
            - name: nginx-logs-volume
              mountPath: /var/log/nginx

        # Container 2: Custom Go Invalidator Sidecar
        - name: invalidator-sidecar
          image: hermes/invalidator-sidecar:1.0.2
          imagePullPolicy: Never
          env:
            - name: KAFKA_BROKER
              value: "hermes-kafka-kafka-bootstrap.kafka.svc.cluster.local:9092"
            - name: KAFKA_TOPIC
              value: "cache-invalidation-events"
          volumeMounts:
            - name: shared-cache-volume
              mountPath: /var/cache/nginx

        # 3: Prometheus Log Exporter Sidecar
        - name: log-exporter-sidecar
          image: quay.io/martinhelmich/prometheus-nginxlog-exporter:v1.11.0
          ports:
            - containerPort: 4040
          volumeMounts:
            - name: nginx-logs-volume
              mountPath: /var/log/nginx
            - name: exporter-config-volume
              mountPath: /etc/prometheus-nginxlog-exporter/config.yml
              subPath: config.yml
          args: [ "-config-file", "/etc/prometheus-nginxlog-exporter/config.yml" ]
      volumes:
        - name: nginx-config-volume
          configMap:
            name: edge-nginx-config
        - name: shared-cache-volume
          emptyDir: {}
        - name: nginx-logs-volume
          emptyDir: { }
        - name: exporter-config-volume
          configMap:
            name: edge-exporter-config
---
apiVersion: v1
kind: Service
metadata:
  name: eu-edge-service
  labels:
    app: eu-edge
    layer: edge-proxy
spec:
  selector:
    app: eu-edge
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: metrics-port
      protocol: TCP
      port: 4040
      targetPort: 4040