apiVersion: apps/v1
kind: Deployment
metadata:
  name: us-edge-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: us-edge
  template:
    metadata:
      labels:
        app: us-edge
    spec:
      # Lock this proxy to the US East region
      nodeSelector:
        topology.kubernetes.io/region: "us-east"
      containers:
        # Container 1: The NGINX Reverse Proxy
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
          volumeMounts:
            # Mount the config map into the container's file system
            - name: nginx-config-volume
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            # Mount the shared cache volume
            - name: shared-cache-volume
              mountPath: /var/cache/nginx

        # Container 2: Custom Go Invalidator Sidecar
        - name: invalidator-sidecar
          image: hermes/invalidator-sidecar:1.0.1
          imagePullPolicy: Never
          env:
            # Strimzi automatically creates this internal DNS name for our kafka broker
            - name: KAFKA_BROKER
              value: "hermes-kafka-kafka-bootstrap.kafka.svc.cluster.local:9092"
            - name: KAFKA_TOPIC
              value: "cache-invalidation-events"
          volumeMounts:
              - name: shared-cache-volume
                mountPath: /var/cache/nginx
      volumes:
        - name: nginx-config-volume
          configMap:
            name: edge-nginx-config
        - name: shared-cache-volume
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: us-edge-service
spec:
  selector:
    app: us-edge
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80